language: node_js
node_js:
- '7'
env:
  global:
  - secure: XHc8e7Armt1/vjFShAg4KpWfLoefgRaKGvK9QDiHnwUeERxrAu1pmTvWZSzBcPyTOR4aAZjpNE8S/N3F42sbCdk5xHQY1JEQnBdt6O433zScWCB67uGF6aBZkIUARWelYiC+3fg5huzILRLIGNBzeDfzx4VWyrlDqddBLmuLGUTPvRv10zpbLfmgY5HpkCLJDGFWkVxnOSfi3FJ2PjiP8Y0jCkD0RAu2DareJtHWYJddivi+iGDnzTuDWaGr7cvhpCCmUFn5BGWDfAA4N7Gw0jFUPh5uyTeoULGNOYFB63G4LpbFGgGkEEzLwW5hoLgBmCjqu0Riod0Em1YwY5oHp00r6beays7LjUDFsRNko/ieO4NoCSbHIxd5VJiA98H7oKvU1u6V01Q3uJBySSA0vXuPeeL7MxA75Ooqy5CCKy3lj3QYSY/j6W184f0BQGa2yXI8Qp8lbO3GQkwqyB9xux4sIOy5e4zE/sXss5bACgPUZ7Tn+np95ujy5RcIb+Lk4JKcnNty2KLZVdfNCMW8o5d6qVhaEwI7sgdO4fWWOdcxr4TB/isEm5HLKHfdxDaVxNHYqBkNla8P7vkNP+TT+fkfzULO19/tN6+M2NQRekYK8SLAqo+cyXwlOfrxYB2Q/XEAA92UQaD3Jco7uPlm7lE6jwvX+wOA6lt7L2kAzaQ=
  - secure: lMlnfb99kluJpAt3XPPPjA+1wFyqttShORRr0eyZJYKGJeU9xGcp3CUdX3kmAXdenUlRrLavpWCW8u+OeAiSDx/DvM/a64wxrF5sZHuH4dBA1ZjcZlT0UeNBnAczbNtJVBx2wEWC4uCxVyquqxd6D58Wf4oHRAlRbT9saRGGrA0htoh05ejFCRlaUUwt8yAHoONbd77v+j/KVGYxD25GW92VesYHNmCy1K3dpxvuAWXiDm3PAmfV+jpb3ngEWJEGxkr1VfQfVI/cn2UE9FvZ2WdzjwnLAjYd5cDzqtyHX+c+PTj6lfP69LpgTX7b7hDyNQ75hVcSsgNU17zQrAR0cNfM5YV0aAuzDkUCUjUQoQ2bHJs2z6/kHwTa0Q3s19WlVxZfx4wsmOmsFFl3Hw1PhathWZ8AiCA9Sbm7uFs8FUgZ43U7Tlq+8wbSRHoBx6Y9ZOYLnbeqdZ2zMG98b6ULUZ6yYRHu3Uk3pcco7PHRHgu3rce6f+hmzoV6Blt7KSVmpIAG/t9Wy0pb2qGw91g/RrBvzbZuax988ecSPAHdtnInWqf/W+MNcmU27ivfZqfPaYpJy2A2wmuHcEjN/ibymfjYLL1v0VoNB0d7QYl9WSIWJG230LPpzCycbkKVjtFQSCJB6a6qphPtLC8qFGKQucIfbyrRqAu3w9d0d/obgmw=
sudo: required
before_script:
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- npm test
- npm run build
after_script:
- echo "machine api.heroku.com" >> ~/.netrc
- echo "  login $HEROKU_USER" >> ~/.netrc
- echo "  password $HEROKU_API_KEY" >> ~/.netrc
- echo "machine git.heroku.com" >> ~/.netrc
- echo "  login $HEROKU_USER" >> ~/.netrc
- echo "  password $HEROKU_API_KEY" >> ~/.netrc
- cd dist/
- git config --global user.email $HEROKU_USER
- git config --global user.name "Travis the Integrator"
- git init
- /usr/local/heroku/bin/heroku git:remote -a consol-100000000000
- git add .
- git commit -m "Deployment from `date`"
#- echo "Host heroku.com" >> ~/.ssh/config
#- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
#- echo "   CheckHostIP no" >> ~/.ssh/config
#- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
#- /usr/local/heroku/bin/heroku keys:clear
#- yes | /usr/local/heroku/bin/heroku keys:add
- yes | git push heroku master --force
