language: node_js
node_js:
- '7'
env:
  global:
    secure: XHc8e7Armt1/vjFShAg4KpWfLoefgRaKGvK9QDiHnwUeERxrAu1pmTvWZSzBcPyTOR4aAZjpNE8S/N3F42sbCdk5xHQY1JEQnBdt6O433zScWCB67uGF6aBZkIUARWelYiC+3fg5huzILRLIGNBzeDfzx4VWyrlDqddBLmuLGUTPvRv10zpbLfmgY5HpkCLJDGFWkVxnOSfi3FJ2PjiP8Y0jCkD0RAu2DareJtHWYJddivi+iGDnzTuDWaGr7cvhpCCmUFn5BGWDfAA4N7Gw0jFUPh5uyTeoULGNOYFB63G4LpbFGgGkEEzLwW5hoLgBmCjqu0Riod0Em1YwY5oHp00r6beays7LjUDFsRNko/ieO4NoCSbHIxd5VJiA98H7oKvU1u6V01Q3uJBySSA0vXuPeeL7MxA75Ooqy5CCKy3lj3QYSY/j6W184f0BQGa2yXI8Qp8lbO3GQkwqyB9xux4sIOy5e4zE/sXss5bACgPUZ7Tn+np95ujy5RcIb+Lk4JKcnNty2KLZVdfNCMW8o5d6qVhaEwI7sgdO4fWWOdcxr4TB/isEm5HLKHfdxDaVxNHYqBkNla8P7vkNP+TT+fkfzULO19/tN6+M2NQRekYK8SLAqo+cyXwlOfrxYB2Q/XEAA92UQaD3Jco7uPlm7lE6jwvX+wOA6lt7L2kAzaQ=
after_script:
  - gem install heroku
  - cd dist/
  - git init
  - git remote add heroku git.heroku.com/consol-100000000000.git
  - git add .
  - git commit -m "Deployment from `date`"
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git push heroku master
